### ISSUE TITLE
Ctrl-D deletes title without confirmation

### ISSUE THREAD

**Issue by ddbruce** [rpitv/rpits#107]
Please add a confirm box to delete a title in the title UI.

**Comment by vreelb** [comment]
So "d" actually deletes a title, not "ctrl-d", [and there has been a confirmation dialog since the shortcut's introduction...](https://github.com/rpitv/rpits/blob/2c7e1ed2bf1d80cc1085ce69c29c9abebcd13e59/im_ui.js#L161)

You may have clicked "Prevent this page from creating additional dialogs." in your own browser, but there is no problem with RPITS.

**Comment by ddbruce** [comment]
It's possible I hit enter by mistake at one point. And yes, it's not Ctrl+D, it's D. I'll modify the title of this issue for posterity.
